#### Importing libraries

In [1]:
import ace_lib as ace
import helpful_functions as hf
import pandas as pd
import requests
#import plotly.express as px

####  Starting the session

In [2]:
s = ace.start_session()

#### Downloading datasets

In [3]:
datasets_df = hf.get_datasets(s)  
datasets_df.head(15)

,id,name,description,category,subcategory,region,delay,universe,coverage,valueScore,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers
0,analyst11,ESG scores,Environmental Social Governance scores that ex...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",GLB,1,MINVOL1M,0.7917,4.0,168,751,197,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
1,analyst14,Estimations of Key Fundamentals,This dataset reports many items from financial...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.5186,4.0,302,1425,926,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
2,analyst15,Earnings forecasts,This dataset provides bottom-up forecast data ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.9929,2.0,542,4055,288,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
3,analyst4,Analyst Estimate Data for Equity,This dataset provides details and aggregations...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.7976,4.0,76,197,18,1.6,[],"[{'type': 'research', 'title': 'Creating D0 Al..."
4,analyst69,Fundamental Analyst Estimates,This dataset is a type of analyst dataset that...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.9369,2.0,560,4100,324,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
5,analyst83,Smart Conference call transcript data,Conference call transcript data provides mainl...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.3880,7.0,11,23,201,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
6,analyst9,Analyst Estimate Daily Data,estimation from analyst,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.8834,4.0,58,140,69,1.6,[],"[{'type': 'research', 'title': 'Research Paper..."
7,fundamental17,Direct Fundamental Data,This dataset contains information about variou...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.7816,3.0,511,2403,733,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
8,fundamental21,ESG Scores Data,This dataset has ESG scores for different ESG ...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.4399,5.0,53,166,173,1.7,[],[]
9,fundamental23,Fundamental Point in Time Data,This dataset gives point in time access to fun...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.6704,3.0,529,3740,886,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
10,fundamental28,Global Fundamental Data,This is a global fundamental dataset providing...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.7785,3.0,531,3102,929,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
11,fundamental31,Additional Factor Model,Market factors made by systematic evaluation p...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.3758,4.0,57,186,81,1.7,[],[]
12,fundamental44,Accounting Quality Models,Machine learning based scores which contains i...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.8863,3.0,106,394,12,1.7,[],[]
13,fundamental6,Company Fundamental Data for Equity,Fundamental database covers most of the world'...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.4203,3.0,210,908,197,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
14,fundamental72,Comprehensive Fundamental Data,This dataset contains comprehensive fundamenta...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.6025,3.0,193,758,524,1.7,[],[]

In [4]:
datasets_df['category'].value_counts()

category
{'id': 'model', 'name': 'Model'}                     16
{'id': 'fundamental', 'name': 'Fundamental'}         10
{'id': 'analyst', 'name': 'Analyst'}                  8
{'id': 'pv', 'name': 'Price Volume'}                  8
{'id': 'news', 'name': 'News'}                        4
{'id': 'option', 'name': 'Option'}                    2
{'id': 'risk', 'name': 'Risk'}                        2
{'id': 'other', 'name': 'Other'}                      1
{'id': 'shortinterest', 'name': 'Short Interest'}     1
Name: count, dtype: int64

#### selecting needed datasets

In [5]:
# select needed datasets
selected_datasets_df = datasets_df
selected_datasets_df.head(15)

,id,name,description,category,subcategory,region,delay,universe,coverage,valueScore,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers
0,analyst11,ESG scores,Environmental Social Governance scores that ex...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",GLB,1,MINVOL1M,0.7917,4.0,168,751,197,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
1,analyst14,Estimations of Key Fundamentals,This dataset reports many items from financial...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.5186,4.0,302,1425,926,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
2,analyst15,Earnings forecasts,This dataset provides bottom-up forecast data ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.9929,2.0,542,4055,288,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
3,analyst4,Analyst Estimate Data for Equity,This dataset provides details and aggregations...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.7976,4.0,76,197,18,1.6,[],"[{'type': 'research', 'title': 'Creating D0 Al..."
4,analyst69,Fundamental Analyst Estimates,This dataset is a type of analyst dataset that...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.9369,2.0,560,4100,324,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
5,analyst83,Smart Conference call transcript data,Conference call transcript data provides mainl...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.3880,7.0,11,23,201,1.6,[],"[{'type': 'discussion', 'title': 'Getting star..."
6,analyst9,Analyst Estimate Daily Data,estimation from analyst,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,MINVOL1M,0.8834,4.0,58,140,69,1.6,[],"[{'type': 'research', 'title': 'Research Paper..."
7,fundamental17,Direct Fundamental Data,This dataset contains information about variou...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.7816,3.0,511,2403,733,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
8,fundamental21,ESG Scores Data,This dataset has ESG scores for different ESG ...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.4399,5.0,53,166,173,1.7,[],[]
9,fundamental23,Fundamental Point in Time Data,This dataset gives point in time access to fun...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.6704,3.0,529,3740,886,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
10,fundamental28,Global Fundamental Data,This is a global fundamental dataset providing...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.7785,3.0,531,3102,929,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
11,fundamental31,Additional Factor Model,Market factors made by systematic evaluation p...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.3758,4.0,57,186,81,1.7,[],[]
12,fundamental44,Accounting Quality Models,Machine learning based scores which contains i...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.8863,3.0,106,394,12,1.7,[],[]
13,fundamental6,Company Fundamental Data for Equity,Fundamental database covers most of the world'...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.4203,3.0,210,908,197,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
14,fundamental72,Comprehensive Fundamental Data,This dataset contains comprehensive fundamenta...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.6025,3.0,193,758,524,1.7,[],[]

In [6]:
filtered_df = datasets_df[datasets_df['category'].apply(lambda x: x['id'] == 'fundamental')]
filtered_df.head(50)

,id,name,description,category,subcategory,region,delay,universe,coverage,valueScore,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers
7,fundamental17,Direct Fundamental Data,This dataset contains information about variou...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.7816,3.0,511,2403,733,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
8,fundamental21,ESG Scores Data,This dataset has ESG scores for different ESG ...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.4399,5.0,53,166,173,1.7,[],[]
9,fundamental23,Fundamental Point in Time Data,This dataset gives point in time access to fun...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.6704,3.0,529,3740,886,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
10,fundamental28,Global Fundamental Data,This is a global fundamental dataset providing...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.7785,3.0,531,3102,929,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
11,fundamental31,Additional Factor Model,Market factors made by systematic evaluation p...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.3758,4.0,57,186,81,1.7,[],[]
12,fundamental44,Accounting Quality Models,Machine learning based scores which contains i...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-models', 'name...",GLB,1,MINVOL1M,0.8863,3.0,106,394,12,1.7,[],[]
13,fundamental6,Company Fundamental Data for Equity,Fundamental database covers most of the world'...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.4203,3.0,210,908,197,1.7,[],"[{'type': 'research', 'title': 'Research Paper..."
14,fundamental72,Comprehensive Fundamental Data,This dataset contains comprehensive fundamenta...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.6025,3.0,193,758,524,1.7,[],[]
15,fundamental93,Earnings Tax Data,This dataset comprehensively studies a wide ra...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.3273,6.0,7,22,23,1.7,[],[]
38,other452,Earnings Tax Data,This dataset comprehensively studies a wide ra...,"{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",GLB,1,MINVOL1M,0.3273,4.0,30,101,23,1.7,[],[]

In [7]:
dataset_id = "fundamental17"
datafields_df = hf.get_datafields(s, region = "ASI",universe = "MINVOL1M", dataset_id=dataset_id)
datafields_df = datafields_df[datafields_df['type'] == 'MATRIX']
datafields_df.head(13)

,id,description,dataset,category,subcategory,region,delay,universe,type,coverage,userCount,alphaCount,pyramidMultiplier,themes
0,fnd17_1_reptoprcexrate,Reporting Currency to base currency exchange rate,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.7809,152,412,1.0,[]
1,fnd17_1_usdtorepexrate,Reporting Currency to USD exchange rate,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.7809,106,296,1.0,[]
2,fnd17_2_reptoprcexrate,Reporting Currency to base currency exchange rate,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.7809,96,228,1.0,[]
3,fnd17_2_usdtorepexrate,Reporting Currency to USD exchange rate,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.7809,90,183,1.0,[]
4,fnd17_2anrhsfcfq,Free Cash Flow per share - most recent quarter...,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.6062,100,285,1.0,[]
5,fnd17_2anrhsfcq,Cash Flow per share - most recent quarter - 1 ...,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.3685,88,249,1.0,[]
6,fnd17_2qe2dtlq,"LT debt/equity - most recent quarter, 1 year ago","{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.6957,92,226,1.0,[]
7,fnd17_2rhsfca,Cash Flow per share - most recent fiscal year - 1,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.7420,70,173,1.0,[]
8,fnd17_2rhsfcfq,Free Cash Flow per share - most recent quarter...,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.6090,58,122,1.0,[]
9,fnd17_2rhsfcq,"Cash Flow per share - most recent quarter, 1 y...","{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.3584,72,321,1.0,[]
10,fnd17_2tcpngmpoa,Operating Margin - 2nd historical fiscal year,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.7426,77,291,1.0,[]
11,fnd17_3_reptoprcexrate,Reporting Currency to base currency exchange rate,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.7809,78,187,1.0,[]
12,fnd17_3_usdtorepexrate,Reporting Currency to USD exchange rate,"{'id': 'fundamental17', 'name': 'Direct Fundam...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",ASI,1,MINVOL1M,MATRIX,0.7809,42,172,1.0,[]

In [8]:
datafields_df.shape

(341, 14)

#### First Alphas simulations

In [17]:
# Create expression list, using selected datafields
expression_list = [f'alpha=(-ts_rank(({x}),500));signed_power(group_neutralize(ts_backfill(alpha,500)*rank(RETURNS),subindustry),1)' for x in datafields_df.id.values.tolist()]
# making alpha settigs for simulation
alpha_list = [ace.generate_alpha(x, decay=2, neutralization= "SLOW", region= "ASI", universe = "MINVOL1M",) for x in expression_list]
# Simulate alpha list
result = ace.simulate_alpha_list_multi(s, alpha_list[102:115])

100%|███████████████████████████████████████████| 5/5 [10:57<00:00, 131.58s/it]

KeyError: 'settings'

In [10]:
# get simulation result 
result_st1 = hf.prettify_result(result, detailed_tests_view=False)
result_st1.head()

,pnl,book_size,long_count,short_count,turnover,returns,drawdown,margin,sharpe,fitness,...,expression,concentrated_weight,high_turnover,is_ladder_sharpe,low_fitness,low_sharpe,low_sub_universe_sharpe,low_turnover,matches_competition,matches_pyramid
0,11660400,20000000,1747,1664,0.8459,0.1126,0.0260,0.000266,4.36,1.59,...,"alpha=(-ts_rank((fnd17_atotce),500));signed_po...",PASS,FAIL,PASS,PASS,PASS,PASS,PASS,WARNING,PASS
1,10987786,20000000,1747,1665,0.8070,0.1061,0.0274,0.000263,4.24,1.54,...,"alpha=(-ts_rank((fnd17_atanbvdolr),500));signe...",PASS,FAIL,PASS,PASS,PASS,PASS,PASS,WARNING,PASS
2,8298770,20000000,1885,1527,0.6165,0.0802,0.0129,0.000260,4.04,1.46,...,"alpha=(-ts_rank((fnd17_ataxrate),500));signed_...",PASS,PASS,PASS,PASS,PASS,PASS,PASS,WARNING,PASS
3,10850325,20000000,1742,1670,0.8216,0.1048,0.0190,0.000255,4.08,1.46,...,"alpha=(-ts_rank((fnd17_ata),500));signed_power...",PASS,FAIL,FAIL,PASS,PASS,PASS,PASS,WARNING,PASS
4,10685956,20000000,1739,1672,0.8362,0.1032,0.0205,0.000247,4.12,1.45,...,"alpha=(-ts_rank((fnd17_atmtt),500));signed_pow...",PASS,FAIL,PASS,PASS,PASS,PASS,PASS,WARNING,PASS

#### Alpha submission

In [11]:
#to take a look at the combined result of all new alphas

is_tests_df = hf.concat_is_tests(result)
is_tests_df.head()

,alpha_id,competitions,endDate,limit,multiplier,name,pyramids,result,startDate,value,year
0,wYZY5V5,NaN,NaN,1.58,NaN,LOW_SHARPE,NaN,PASS,NaN,4.0800,NaN
1,wYZY5V5,NaN,NaN,1.00,NaN,LOW_FITNESS,NaN,PASS,NaN,1.4600,NaN
2,wYZY5V5,NaN,NaN,0.01,NaN,LOW_TURNOVER,NaN,PASS,NaN,0.8216,NaN
3,wYZY5V5,NaN,NaN,0.70,NaN,HIGH_TURNOVER,NaN,FAIL,NaN,0.8216,NaN
4,wYZY5V5,NaN,NaN,NaN,NaN,CONCENTRATED_WEIGHT,NaN,PASS,NaN,NaN,NaN

In [12]:
#making a list of failed alphas
failed_alphas = is_tests_df.query('result=="FAIL"')['alpha_id'].unique()

#making a list of passed alphas
passed_alphas = list(set(is_tests_df['alpha_id']).difference(failed_alphas))

In [13]:
print(f'Failed alphas:{failed_alphas}\nPassed alphas:{passed_alphas}')

Failed alphas:['wYZY5V5' 'V6a6Xnw' 'A0N0n6X' 'Q3b3EQQ' '6rjrzEL' 'pPRPKg3']
Passed alphas:['aLbLoO6', '6rjrzwL', 'j3A31ZW', '9VjVJJ9']

In [14]:
#calling submit_alpha on all alphas that have passed the submission tests

submit_result = {alpha_id: ace.submit_alpha(s, alpha_id) for alpha_id in passed_alphas}

In [15]:
#submit_result will have return values from the submit_result function

submit_result

{'aLbLoO6': True, '6rjrzwL': False, 'j3A31ZW': True, '9VjVJJ9': False}