In [37]:
import pandas as  pd
import numpy as np
from numpy.random import randn

In [38]:
my_data = randn(4,3) #Rows and Colums
my_rows = ["A", "B", "C", "D"]
my_cols = ["Monay", "Tuesday", "Friday"]

In [39]:
# Create DataFrame
my_df = pd.DataFrame(my_data, my_rows, my_cols)
my_df

      Monay   Tuesday    Friday
A  1.349763 -0.190326 -0.938884
B  0.673253  0.494051 -2.156624
C -0.275663 -0.313195  0.865137
D  0.497121 -0.409066 -0.320555

In [40]:
# Import csv file
my_df2 = pd.read_csv('products-100.csv')
my_df2

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [41]:
# Pulling out rows
my_df2.loc[0]

Index                                                       1
Name                     Compact Printer Air Advanced Digital
Description     Situation organization these memory much off.
Brand                                 Garner, Boyle and Flynn
Category                                   Books & Stationery
Price                                                     265
Currency                                                  USD
Stock                                                     774
EAN                                             2091465262179
Color                                             ForestGreen
Size                                                    Large
Availability                                        pre_order
Internal ID                                                56
Name: 0, dtype: object

In [42]:
my_df2.head(7)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
5,6,Radio,Character prove growth contain serious customer.,"Benjamin, Nelson and Hancock",Skincare,426,USD,549,1150028980156,CornflowerBlue,30x40 cm,pre_order,60
6,7,Ultra Projector Oven Thermostat Prime Advanced,Pattern possible look necessary indicate work ...,"Mccoy, Waters and Rose",Laptops & Computers,68,USD,870,5029747624534,Purple,S,discontinued,86

In [43]:
my_df2.tail(7)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
93,94,Scanner,Draw material quickly most.,"Wang, Ayala and Bowen",Cleaning Supplies,472,USD,63,7794860625802,ForestGreen,12x18 in,backorder,8
94,95,Ultra Radio Radio,Shoulder red boy away if.,Maldonado-Ritter,Haircare,382,USD,639,3611080124547,Aquamarine,12x18 in,pre_order,48
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [44]:
my_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         100 non-null    int64
 1   Name          100 non-null    object
 2   Description   100 non-null    object
 3   Brand         100 non-null    object
 4   Category      100 non-null    object
 5   Price         100 non-null    int64
 6   Currency      100 non-null    object
 7   Stock         100 non-null    int64
 8   EAN           100 non-null    int64
 9   Color         100 non-null    object
 10  Size          100 non-null    object
 11  Availability  100 non-null    object
 12  Internal ID   100 non-null    int64
dtypes: int64(5), object(8)
memory usage: 10.3+ KB

In [45]:
my_df2.shape

(100, 13)

In [46]:
my_df2.Brand

0         Garner, Boyle and Flynn
1                     Mueller Inc
2      Lawson, Keller and Winters
3              Gallagher and Sons
4                       Irwin LLC
                 ...
95                   Atkinson Inc
96                       Shea Ltd
97                       West Ltd
98       Bell, Gamble and Barrett
99    Hebert, Hughes and Trujillo
Name: Brand, Length: 100, dtype: object

In [47]:
my_df2['Color'].value_counts()

Color
Cyan                4
MidnightBlue        3
Sienna              3
ForestGreen         2
MediumOrchid        2
                   ..
MediumAquaMarine    1
BlueViolet          1
Navy                1
DeepSkyBlue         1
OldLace             1
Name: count, Length: 72, dtype: int64

In [48]:
my_df2.insert(5, "Rating",["No Rating"]*len(my_df2), True )
my_df2

,Index,Name,Description,Brand,Category,Rating,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,No Rating,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,No Rating,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,No Rating,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,No Rating,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,No Rating,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,No Rating,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,No Rating,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,No Rating,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,No Rating,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,No Rating,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [49]:
my_df3 = my_df2.assign(InDemand=[True]*len(my_df2))
my_df3

,Index,Name,Description,Brand,Category,Rating,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID,InDemand
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,No Rating,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56,True
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,No Rating,502,USD,81,5286196620740,Black,8x10 in,in_stock,29,True
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,No Rating,227,USD,726,1282898648918,SlateGray,XS,in_stock,70,True
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,No Rating,121,USD,896,3879177514583,PaleGreen,L,discontinued,31,True
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,No Rating,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,No Rating,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55,True
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,No Rating,289,USD,727,9265397743935,White,Extra Large,backorder,25,True
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,No Rating,232,USD,998,5505866454530,OldLace,Small,limited_stock,20,True
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,No Rating,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5,True
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,No Rating,71,USD,518,8264263605712,Brown,Medium,limited_stock,3,True

In [50]:
 my_df2.drop("Rating", axis=1)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [51]:
my_df2

,Index,Name,Description,Brand,Category,Rating,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,No Rating,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,No Rating,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,No Rating,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,No Rating,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,No Rating,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,No Rating,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,No Rating,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,No Rating,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,No Rating,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,No Rating,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [52]:
my_df2.drop("Rating", axis=1, inplace=True)

In [53]:
my_df2.drop("Index", axis=1, inplace=True)

In [54]:
my_df2

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...
95,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [55]:
my_df2.iloc[3]

Name               Advanced Router Rechargeable
Description     For force gas energy six laugh.
Brand                        Gallagher and Sons
Category                     Kitchen Appliances
Price                                       121
Currency                                    USD
Stock                                       896
EAN                               3879177514583
Color                                 PaleGreen
Size                                          L
Availability                       discontinued
Internal ID                                  31
Name: 3, dtype: object

In [56]:
my_df2.loc[3, "Name"]

'Advanced Router Rechargeable'

In [57]:
my_df2.loc[[1,3,8,10], ["Brand", "Price", "Currency"]]

                           Brand  Price Currency
1                    Mueller Inc    502      USD
3             Gallagher and Sons    121      USD
8   Edwards, Odonnell and Conley    454      USD
10                    Russo-West    257      USD

In [58]:
my_df2 == "Black"

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False

In [59]:
my_df2[my_df2 == "Black"]

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Black,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
my_df2[my_df2 == "Black"]["Color"]

0       NaN
1     Black
2       NaN
3       NaN
4       NaN
      ...
95      NaN
96      NaN
97      NaN
98      NaN
99      NaN
Name: Color, Length: 100, dtype: object

In [61]:
my_df2[my_df2["Color"] == "Cyan"]

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
18,Eco Freezer Powerbank Watch,Of price visit interesting enter three set.,"Pruitt, Higgins and Barnett",Cleaning Supplies,340,USD,618,6340907128242,Cyan,S,limited_stock,21
51,Rechargeable Tablet Plus Portable Mini,Expect question how sound.,Mooney-Gonzales,Fragrances,820,USD,535,8183922928019,Cyan,100x200 mm,in_stock,19
65,Treadmill,Vote only run modern.,"Frost, Christensen and Burnett",Women's Clothing,731,USD,744,4598541150958,Cyan,5x7 in,out_of_stock,70
84,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64

In [62]:
my_df2[(my_df2["Color"] == "Cyan") & (my_df2["Availability"] == "limited_stock")]

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
18,Eco Freezer Powerbank Watch,Of price visit interesting enter three set.,"Pruitt, Higgins and Barnett",Cleaning Supplies,340,USD,618,6340907128242,Cyan,S,limited_stock,21
84,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64

In [63]:
my_df2[(my_df2["Color"] == "Cyan") | (my_df2["Availability"] == "limited_stock")]

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
15,Automatic Watch Lite Sense,As east entire positive source their.,"Reid, Chase and Ballard",Team Sports,316,USD,329,3500722785805,Tan,5x7 in,limited_stock,44
18,Eco Freezer Powerbank Watch,Of price visit interesting enter three set.,"Pruitt, Higgins and Barnett",Cleaning Supplies,340,USD,618,6340907128242,Cyan,S,limited_stock,21
25,Mini Iron Drone Wireless Pro,From Congress low.,Khan-Parrish,Cycling,909,USD,797,9496081864722,CadetBlue,XXL,limited_stock,93
27,Wireless Webcam Stove Grill,Pull at improve health also animal forward per...,Henry Group,Clothing & Apparel,858,USD,912,7097613907430,LightSalmon,50x70 cm,limited_stock,43
30,Silent Printer Fan Shaver,Region week yet weight.,Love LLC,Sports & Outdoors,102,USD,669,5564792899662,MediumSpringGreen,L,limited_stock,14
32,Advanced Microphone Cooler Eco,Most other newspaper beyond real.,"Morales, Weaver and Fernandez",Smartphones,904,USD,532,7107438924403,LightCyan,Extra Large,limited_stock,86
40,Silent Dock Fast,Speak not hospital bit part.,"May, Hendrix and Robbins",Fishing & Hunting,100,USD,802,938364240247,CadetBlue,M,limited_stock,12
42,Rechargeable Projector Pro,Bank everything ago girl.,"Levine, Martin and Mccann",Home Decor,935,USD,55,655296358115,SlateBlue,XL,limited_stock,52
45,Digital Stove Silent Pro,Suffer range between step mention peace prepare.,"Suarez, Riddle and Sanders",Health & Wellness,161,USD,349,5367012957872,OrangeRed,Extra Large,limited_stock,9
47,Clock,Onto story what job require.,"Malone, Jacobson and Hudson",Team Sports,731,USD,664,1382809012286,FloralWhite,S,limited_stock,55
51,Rechargeable Tablet Plus Portable Mini,Expect question how sound.,Mooney-Gonzales,Fragrances,820,USD,535,8183922928019,Cyan,100x200 mm,in_stock,19
65,Treadmill,Vote only run modern.,"Frost, Christensen and Burnett",Women's Clothing,731,USD,744,4598541150958,Cyan,5x7 in,out_of_stock,70
69,Compact Mouse Mouse Router Mini,Occur miss son Democrat happy.,Barry PLC,Smartwatches,5,USD,247,252926529077,PapayaWhip,10x10 cm,limited_stock,79
84,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64
88,Fast Vacuum Cooler,Explain six firm recent rock skin.,Blair-Russell,Sports & Outdoors,307,USD,320,4874329354658,LightSalmon,L,limited_stock,5
95,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
97,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [64]:
my_df3.drop("Index", axis=1, inplace=True)

In [65]:
my_df3["Condition"] = ["Good"]*len(my_df3)
my_df3

,Name,Description,Brand,Category,Rating,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID,InDemand,Condition
0,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,No Rating,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56,True,Good
1,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,No Rating,502,USD,81,5286196620740,Black,8x10 in,in_stock,29,True,Good
2,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,No Rating,227,USD,726,1282898648918,SlateGray,XS,in_stock,70,True,Good
3,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,No Rating,121,USD,896,3879177514583,PaleGreen,L,discontinued,31,True,Good
4,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,No Rating,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10,True,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,No Rating,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55,True,Good
96,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,No Rating,289,USD,727,9265397743935,White,Extra Large,backorder,25,True,Good
97,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,No Rating,232,USD,998,5505866454530,OldLace,Small,limited_stock,20,True,Good
98,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,No Rating,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5,True,Good
99,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,No Rating,71,USD,518,8264263605712,Brown,Medium,limited_stock,3,True,Good

In [68]:
stuff = { "A":[1,2,3], "B":[4,5,6], "C":[7,8,9], "D":[10,11,12]}
my_df4 = pd.DataFrame(stuff)
my_df4

   A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12